kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind

# Uncomment below if you want to use Calico
# networking:
#  disableDefaultCNI: true
#  podSubnet: 192.168.0.0/16

nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 4443
    protocol: TCP
- role: worker
- role: worker
- role: worker