{{- if or .Values.podSecurityPolicy.enabled (not .Values.rbac.clusterscoped) }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "goldpinger.fullname" . }}-pod-security-policy
  labels:
    app.kubernetes.io/name: {{ include "goldpinger.name" . }}
    helm.sh/chart: {{ include "goldpinger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  kind: Role
  name: {{ include "goldpinger.fullname" . }}-pod-security-policy
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "goldpinger.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
